name: GitHub Metrics
on:
  schedule: [{cron: "0 6 * * *"}] # daily at 06:00 UTC
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # REQUIRED
          token: ${{ secrets.METRICS_TOKEN }}
          user: Madumita24
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Phoenix

          # Common plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_stars: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
